version: 3

project:
  name: serenibase
  target: production

paths:
  only:
    - .

analyze:
  modules:
    - name: serenibase
      path: .
      target: production

exclude:
  - tests/**
  - docs/**
  
