version: "3.9"

services:
  serenibase-rest:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - serenibase-network

  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - serenibase-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d serenibase"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s


volumes:
  postgres_data:
  minio_data:

networks:
  serenibase-network:
    driver: bridge
