sonar.projectKey=aptlogica_sereni-base
sonar.organization=aptlogica
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=tests/handlers/mocks/**
