sonar.projectKey=aptlogica_sereni-base_58d1e56c-7e79-4847-b5b2-68b244b3b65b

sonar.language=go
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=tests/handlers/mocks/**