sonar.projectKey=aptlogica_sereni-base
sonar.organization=aptlogica
sonar.language=go
sonar.sources=cmd,internal
sonar.tests=tests
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions==**/*_test.go,tests/**
sonar.coverage.exclusions=cmd/server/main.go,docs/**,**/docs.go