// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces/auth_management.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/interfaces/auth_management.go -destination=tests/handlers/mocks/mock_auth_management.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aptlogica/sereni-base/internal/dto"
	tenant "github.com/aptlogica/sereni-base/internal/models/tenant"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthManagementService is a mock of AuthManagementService interface.
type MockAuthManagementService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthManagementServiceMockRecorder
	isgomock struct{}
}

// MockAuthManagementServiceMockRecorder is the mock recorder for MockAuthManagementService.
type MockAuthManagementServiceMockRecorder struct {
	mock *MockAuthManagementService
}

// NewMockAuthManagementService creates a new mock instance.
func NewMockAuthManagementService(ctrl *gomock.Controller) *MockAuthManagementService {
	mock := &MockAuthManagementService{ctrl: ctrl}
	mock.recorder = &MockAuthManagementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthManagementService) EXPECT() *MockAuthManagementServiceMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *MockAuthManagementService) ActivateUser(ctx context.Context, schema, userID, reqBy string) (dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser", ctx, schema, userID, reqBy)
	ret0, _ := ret[0].(dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivateUser indicates an expected call of ActivateUser.
func (mr *MockAuthManagementServiceMockRecorder) ActivateUser(ctx, schema, userID, reqBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*MockAuthManagementService)(nil).ActivateUser), ctx, schema, userID, reqBy)
}

// AddUser mocks base method.
func (m *MockAuthManagementService) AddUser(ctx context.Context, schema string, userData dto.AddUserRequest, reqBy string) (tenant.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, schema, userData, reqBy)
	ret0, _ := ret[0].(tenant.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUser indicates an expected call of AddUser.
func (mr *MockAuthManagementServiceMockRecorder) AddUser(ctx, schema, userData, reqBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockAuthManagementService)(nil).AddUser), ctx, schema, userData, reqBy)
}

// AssignUserToWorkspace mocks base method.
func (m *MockAuthManagementService) AssignUserToWorkspace(ctx context.Context, schema string, req dto.CreateMemberRequest, reqBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignUserToWorkspace", ctx, schema, req, reqBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignUserToWorkspace indicates an expected call of AssignUserToWorkspace.
func (mr *MockAuthManagementServiceMockRecorder) AssignUserToWorkspace(ctx, schema, req, reqBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignUserToWorkspace", reflect.TypeOf((*MockAuthManagementService)(nil).AssignUserToWorkspace), ctx, schema, req, reqBy)
}

// BulkAddBaseMembers mocks base method.
func (m *MockAuthManagementService) BulkAddBaseMembers(ctx context.Context, schema, baseID string, req dto.BulkAddBaseMembersRequest, userID string) (dto.BulkAddMembersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkAddBaseMembers", ctx, schema, baseID, req, userID)
	ret0, _ := ret[0].(dto.BulkAddMembersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkAddBaseMembers indicates an expected call of BulkAddBaseMembers.
func (mr *MockAuthManagementServiceMockRecorder) BulkAddBaseMembers(ctx, schema, baseID, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkAddBaseMembers", reflect.TypeOf((*MockAuthManagementService)(nil).BulkAddBaseMembers), ctx, schema, baseID, req, userID)
}

// BulkAddMembers mocks base method.
func (m *MockAuthManagementService) BulkAddMembers(ctx context.Context, schema string, req dto.BulkAddMembersRequest, userID string) (dto.BulkAddMembersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkAddMembers", ctx, schema, req, userID)
	ret0, _ := ret[0].(dto.BulkAddMembersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkAddMembers indicates an expected call of BulkAddMembers.
func (mr *MockAuthManagementServiceMockRecorder) BulkAddMembers(ctx, schema, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkAddMembers", reflect.TypeOf((*MockAuthManagementService)(nil).BulkAddMembers), ctx, schema, req, userID)
}

// DeactivateUser mocks base method.
func (m *MockAuthManagementService) DeactivateUser(ctx context.Context, schema, userID, reqBy string) (dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUser", ctx, schema, userID, reqBy)
	ret0, _ := ret[0].(dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeactivateUser indicates an expected call of DeactivateUser.
func (mr *MockAuthManagementServiceMockRecorder) DeactivateUser(ctx, schema, userID, reqBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUser", reflect.TypeOf((*MockAuthManagementService)(nil).DeactivateUser), ctx, schema, userID, reqBy)
}

// DeleteUserCompletely mocks base method.
func (m *MockAuthManagementService) DeleteUserCompletely(ctx context.Context, schema, userID, reqBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserCompletely", ctx, schema, userID, reqBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserCompletely indicates an expected call of DeleteUserCompletely.
func (mr *MockAuthManagementServiceMockRecorder) DeleteUserCompletely(ctx, schema, userID, reqBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserCompletely", reflect.TypeOf((*MockAuthManagementService)(nil).DeleteUserCompletely), ctx, schema, userID, reqBy)
}

// EditUser mocks base method.
func (m *MockAuthManagementService) EditUser(ctx context.Context, schema string, userData dto.EditUserRequest, reqBy string) (dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditUser", ctx, schema, userData, reqBy)
	ret0, _ := ret[0].(dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditUser indicates an expected call of EditUser.
func (mr *MockAuthManagementServiceMockRecorder) EditUser(ctx, schema, userData, reqBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditUser", reflect.TypeOf((*MockAuthManagementService)(nil).EditUser), ctx, schema, userData, reqBy)
}

// ForgotPassword mocks base method.
func (m *MockAuthManagementService) ForgotPassword(ctx context.Context, req dto.ForgotPasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPassword", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForgotPassword indicates an expected call of ForgotPassword.
func (mr *MockAuthManagementServiceMockRecorder) ForgotPassword(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPassword", reflect.TypeOf((*MockAuthManagementService)(nil).ForgotPassword), ctx, req)
}

// GetActiveUsersForAssign mocks base method.
func (m *MockAuthManagementService) GetActiveUsersForAssign(ctx context.Context, schema string) ([]dto.UserWithRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUsersForAssign", ctx, schema)
	ret0, _ := ret[0].([]dto.UserWithRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUsersForAssign indicates an expected call of GetActiveUsersForAssign.
func (mr *MockAuthManagementServiceMockRecorder) GetActiveUsersForAssign(ctx, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUsersForAssign", reflect.TypeOf((*MockAuthManagementService)(nil).GetActiveUsersForAssign), ctx, schema)
}

// GetAuthProviderUrl mocks base method.
func (m *MockAuthManagementService) GetAuthProviderUrl(provider string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthProviderUrl", provider)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthProviderUrl indicates an expected call of GetAuthProviderUrl.
func (mr *MockAuthManagementServiceMockRecorder) GetAuthProviderUrl(provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthProviderUrl", reflect.TypeOf((*MockAuthManagementService)(nil).GetAuthProviderUrl), provider)
}

// GetBaseMembers mocks base method.
func (m *MockAuthManagementService) GetBaseMembers(ctx context.Context, schema, baseID string) ([]dto.WorkspaceMemberResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseMembers", ctx, schema, baseID)
	ret0, _ := ret[0].([]dto.WorkspaceMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBaseMembers indicates an expected call of GetBaseMembers.
func (mr *MockAuthManagementServiceMockRecorder) GetBaseMembers(ctx, schema, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseMembers", reflect.TypeOf((*MockAuthManagementService)(nil).GetBaseMembers), ctx, schema, baseID)
}

// GetBaseMembersWithRole mocks base method.
func (m *MockAuthManagementService) GetBaseMembersWithRole(ctx context.Context, schema, baseID string) ([]dto.UserWithRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseMembersWithRole", ctx, schema, baseID)
	ret0, _ := ret[0].([]dto.UserWithRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBaseMembersWithRole indicates an expected call of GetBaseMembersWithRole.
func (mr *MockAuthManagementServiceMockRecorder) GetBaseMembersWithRole(ctx, schema, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseMembersWithRole", reflect.TypeOf((*MockAuthManagementService)(nil).GetBaseMembersWithRole), ctx, schema, baseID)
}

// GetUsers mocks base method.
func (m *MockAuthManagementService) GetUsers(ctx context.Context, schema string) ([]dto.UserWithRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx, schema)
	ret0, _ := ret[0].([]dto.UserWithRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockAuthManagementServiceMockRecorder) GetUsers(ctx, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockAuthManagementService)(nil).GetUsers), ctx, schema)
}

// GetWorkspaceMembers mocks base method.
func (m *MockAuthManagementService) GetWorkspaceMembers(ctx context.Context, schema, workspaceID string) ([]dto.WorkspaceMemberResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceMembers", ctx, schema, workspaceID)
	ret0, _ := ret[0].([]dto.WorkspaceMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceMembers indicates an expected call of GetWorkspaceMembers.
func (mr *MockAuthManagementServiceMockRecorder) GetWorkspaceMembers(ctx, schema, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceMembers", reflect.TypeOf((*MockAuthManagementService)(nil).GetWorkspaceMembers), ctx, schema, workspaceID)
}

// GetWorkspaceMembersWithRole mocks base method.
func (m *MockAuthManagementService) GetWorkspaceMembersWithRole(ctx context.Context, schema, workspaceID string) ([]dto.UserWithRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceMembersWithRole", ctx, schema, workspaceID)
	ret0, _ := ret[0].([]dto.UserWithRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceMembersWithRole indicates an expected call of GetWorkspaceMembersWithRole.
func (mr *MockAuthManagementServiceMockRecorder) GetWorkspaceMembersWithRole(ctx, schema, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceMembersWithRole", reflect.TypeOf((*MockAuthManagementService)(nil).GetWorkspaceMembersWithRole), ctx, schema, workspaceID)
}

// HandleKeycloakCallback mocks base method.
func (m *MockAuthManagementService) HandleKeycloakCallback(ctx context.Context, code string) (dto.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleKeycloakCallback", ctx, code)
	ret0, _ := ret[0].(dto.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleKeycloakCallback indicates an expected call of HandleKeycloakCallback.
func (mr *MockAuthManagementServiceMockRecorder) HandleKeycloakCallback(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleKeycloakCallback", reflect.TypeOf((*MockAuthManagementService)(nil).HandleKeycloakCallback), ctx, code)
}

// Login mocks base method.
func (m *MockAuthManagementService) Login(ctx context.Context, email, password string) (dto.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(dto.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthManagementServiceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthManagementService)(nil).Login), ctx, email, password)
}

// Logout mocks base method.
func (m *MockAuthManagementService) Logout(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthManagementServiceMockRecorder) Logout(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthManagementService)(nil).Logout), ctx, refreshToken)
}

// RefreshToken mocks base method.
func (m *MockAuthManagementService) RefreshToken(ctx context.Context, req dto.RefreshTokenRequest) (dto.TokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, req)
	ret0, _ := ret[0].(dto.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthManagementServiceMockRecorder) RefreshToken(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthManagementService)(nil).RefreshToken), ctx, req)
}

// RegisterOwner mocks base method.
func (m *MockAuthManagementService) RegisterOwner(ctx context.Context, req dto.RegisterRequest) (dto.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterOwner", ctx, req)
	ret0, _ := ret[0].(dto.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterOwner indicates an expected call of RegisterOwner.
func (mr *MockAuthManagementServiceMockRecorder) RegisterOwner(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOwner", reflect.TypeOf((*MockAuthManagementService)(nil).RegisterOwner), ctx, req)
}

// RemoveAccessMemberByID mocks base method.
func (m *MockAuthManagementService) RemoveAccessMemberByID(ctx context.Context, schema, accessMemberID, reqBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAccessMemberByID", ctx, schema, accessMemberID, reqBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAccessMemberByID indicates an expected call of RemoveAccessMemberByID.
func (mr *MockAuthManagementServiceMockRecorder) RemoveAccessMemberByID(ctx, schema, accessMemberID, reqBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAccessMemberByID", reflect.TypeOf((*MockAuthManagementService)(nil).RemoveAccessMemberByID), ctx, schema, accessMemberID, reqBy)
}

// RemoveUser mocks base method.
func (m *MockAuthManagementService) RemoveUser(ctx context.Context, schema, userID, reqBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUser", ctx, schema, userID, reqBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUser indicates an expected call of RemoveUser.
func (mr *MockAuthManagementServiceMockRecorder) RemoveUser(ctx, schema, userID, reqBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUser", reflect.TypeOf((*MockAuthManagementService)(nil).RemoveUser), ctx, schema, userID, reqBy)
}

// RemoveUserFromBase mocks base method.
func (m *MockAuthManagementService) RemoveUserFromBase(ctx context.Context, schema, baseID, userID, reqBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromBase", ctx, schema, baseID, userID, reqBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromBase indicates an expected call of RemoveUserFromBase.
func (mr *MockAuthManagementServiceMockRecorder) RemoveUserFromBase(ctx, schema, baseID, userID, reqBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromBase", reflect.TypeOf((*MockAuthManagementService)(nil).RemoveUserFromBase), ctx, schema, baseID, userID, reqBy)
}

// RemoveUserFromWorkspace mocks base method.
func (m *MockAuthManagementService) RemoveUserFromWorkspace(ctx context.Context, schema, workspaceID, userID, reqBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromWorkspace", ctx, schema, workspaceID, userID, reqBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromWorkspace indicates an expected call of RemoveUserFromWorkspace.
func (mr *MockAuthManagementServiceMockRecorder) RemoveUserFromWorkspace(ctx, schema, workspaceID, userID, reqBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromWorkspace", reflect.TypeOf((*MockAuthManagementService)(nil).RemoveUserFromWorkspace), ctx, schema, workspaceID, userID, reqBy)
}

// ResendOTP mocks base method.
func (m *MockAuthManagementService) ResendOTP(ctx context.Context, req dto.ResendOTPRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendOTP", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResendOTP indicates an expected call of ResendOTP.
func (mr *MockAuthManagementServiceMockRecorder) ResendOTP(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendOTP", reflect.TypeOf((*MockAuthManagementService)(nil).ResendOTP), ctx, req)
}

// ResetPassword mocks base method.
func (m *MockAuthManagementService) ResetPassword(ctx context.Context, req dto.ResetPasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockAuthManagementServiceMockRecorder) ResetPassword(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockAuthManagementService)(nil).ResetPassword), ctx, req)
}

// UpdatePassword mocks base method.
func (m *MockAuthManagementService) UpdatePassword(ctx context.Context, schema, userID string, updateData dto.UpdateUserPasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, schema, userID, updateData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockAuthManagementServiceMockRecorder) UpdatePassword(ctx, schema, userID, updateData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockAuthManagementService)(nil).UpdatePassword), ctx, schema, userID, updateData)
}

// ValidateToken mocks base method.
func (m *MockAuthManagementService) ValidateToken(ctx context.Context, token string) (dto.TokenValidationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(dto.TokenValidationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockAuthManagementServiceMockRecorder) ValidateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockAuthManagementService)(nil).ValidateToken), ctx, token)
}

// VerifyEmail mocks base method.
func (m *MockAuthManagementService) VerifyEmail(ctx context.Context, req dto.VerifyEmailRequest) (dto.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, req)
	ret0, _ := ret[0].(dto.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockAuthManagementServiceMockRecorder) VerifyEmail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockAuthManagementService)(nil).VerifyEmail), ctx, req)
}

// VerifyToken mocks base method.
func (m *MockAuthManagementService) VerifyToken(ctx context.Context, token string) (dto.TokenValidationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", ctx, token)
	ret0, _ := ret[0].(dto.TokenValidationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockAuthManagementServiceMockRecorder) VerifyToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockAuthManagementService)(nil).VerifyToken), ctx, token)
}
