// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces/user_management.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/interfaces/user_management.go -destination=tests/handlers/mocks/mock_user_management.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"
	dto "github.com/aptlogica/sereni-base/internal/dto"
	tenant "github.com/aptlogica/sereni-base/internal/models/tenant"

	gomock "go.uber.org/mock/gomock"
)

// MockUserManagementService is a mock of UserManagementService interface.
type MockUserManagementService struct {
	ctrl     *gomock.Controller
	recorder *MockUserManagementServiceMockRecorder
	isgomock struct{}
}

// MockUserManagementServiceMockRecorder is the mock recorder for MockUserManagementService.
type MockUserManagementServiceMockRecorder struct {
	mock *MockUserManagementService
}

// NewMockUserManagementService creates a new mock instance.
func NewMockUserManagementService(ctrl *gomock.Controller) *MockUserManagementService {
	mock := &MockUserManagementService{ctrl: ctrl}
	mock.recorder = &MockUserManagementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserManagementService) EXPECT() *MockUserManagementServiceMockRecorder {
	return m.recorder
}

// AddAvatar mocks base method.
func (m *MockUserManagementService) AddAvatar(ctx context.Context, schema, userID string, fileHeader *multipart.FileHeader) (dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAvatar", ctx, schema, userID, fileHeader)
	ret0, _ := ret[0].(dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAvatar indicates an expected call of AddAvatar.
func (mr *MockUserManagementServiceMockRecorder) AddAvatar(ctx, schema, userID, fileHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAvatar", reflect.TypeOf((*MockUserManagementService)(nil).AddAvatar), ctx, schema, userID, fileHeader)
}

// CreateUser mocks base method.
func (m *MockUserManagementService) CreateUser(ctx context.Context, schema string, req dto.RegisterRequest) (tenant.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, schema, req)
	ret0, _ := ret[0].(tenant.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserManagementServiceMockRecorder) CreateUser(ctx, schema, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserManagementService)(nil).CreateUser), ctx, schema, req)
}

// DeleteUserCompletely mocks base method.
func (m *MockUserManagementService) DeleteUserCompletely(ctx context.Context, schema, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserCompletely", ctx, schema, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserCompletely indicates an expected call of DeleteUserCompletely.
func (mr *MockUserManagementServiceMockRecorder) DeleteUserCompletely(ctx, schema, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserCompletely", reflect.TypeOf((*MockUserManagementService)(nil).DeleteUserCompletely), ctx, schema, userID)
}

// GetActiveUsersForAssign mocks base method.
func (m *MockUserManagementService) GetActiveUsersForAssign(ctx context.Context, schema string) ([]dto.UserWithRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUsersForAssign", ctx, schema)
	ret0, _ := ret[0].([]dto.UserWithRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUsersForAssign indicates an expected call of GetActiveUsersForAssign.
func (mr *MockUserManagementServiceMockRecorder) GetActiveUsersForAssign(ctx, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUsersForAssign", reflect.TypeOf((*MockUserManagementService)(nil).GetActiveUsersForAssign), ctx, schema)
}

// GetAllUsers mocks base method.
func (m *MockUserManagementService) GetAllUsers(ctx context.Context, schema string) ([]tenant.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx, schema)
	ret0, _ := ret[0].([]tenant.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockUserManagementServiceMockRecorder) GetAllUsers(ctx, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockUserManagementService)(nil).GetAllUsers), ctx, schema)
}

// GetBulkUsers mocks base method.
func (m *MockUserManagementService) GetBulkUsers(ctx context.Context, schema string, ids []string) ([]tenant.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBulkUsers", ctx, schema, ids)
	ret0, _ := ret[0].([]tenant.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBulkUsers indicates an expected call of GetBulkUsers.
func (mr *MockUserManagementServiceMockRecorder) GetBulkUsers(ctx, schema, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBulkUsers", reflect.TypeOf((*MockUserManagementService)(nil).GetBulkUsers), ctx, schema, ids)
}

// GetUserAccessDetails mocks base method.
func (m *MockUserManagementService) GetUserAccessDetails(ctx context.Context, schema, userID, roles, workspaceID string) (dto.UserAccessDetailsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccessDetails", ctx, schema, userID, roles, workspaceID)
	ret0, _ := ret[0].(dto.UserAccessDetailsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccessDetails indicates an expected call of GetUserAccessDetails.
func (mr *MockUserManagementServiceMockRecorder) GetUserAccessDetails(ctx, schema, userID, roles, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccessDetails", reflect.TypeOf((*MockUserManagementService)(nil).GetUserAccessDetails), ctx, schema, userID, roles, workspaceID)
}

// GetUserByEmail mocks base method.
func (m *MockUserManagementService) GetUserByEmail(ctx context.Context, schema, email string) (tenant.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, schema, email)
	ret0, _ := ret[0].(tenant.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserManagementServiceMockRecorder) GetUserByEmail(ctx, schema, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserManagementService)(nil).GetUserByEmail), ctx, schema, email)
}

// GetUserByID mocks base method.
func (m *MockUserManagementService) GetUserByID(ctx context.Context, schema, id string) (tenant.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, schema, id)
	ret0, _ := ret[0].(tenant.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserManagementServiceMockRecorder) GetUserByID(ctx, schema, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserManagementService)(nil).GetUserByID), ctx, schema, id)
}

// GetUserProfileByID mocks base method.
func (m *MockUserManagementService) GetUserProfileByID(ctx context.Context, schema, userID string) (dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileByID", ctx, schema, userID)
	ret0, _ := ret[0].(dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfileByID indicates an expected call of GetUserProfileByID.
func (mr *MockUserManagementServiceMockRecorder) GetUserProfileByID(ctx, schema, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileByID", reflect.TypeOf((*MockUserManagementService)(nil).GetUserProfileByID), ctx, schema, userID)
}

// GetUserRolesAndAccess mocks base method.
func (m *MockUserManagementService) GetUserRolesAndAccess(ctx context.Context, schema, userID string, scopeID *string) ([]dto.UserRolesAccessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRolesAndAccess", ctx, schema, userID, scopeID)
	ret0, _ := ret[0].([]dto.UserRolesAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRolesAndAccess indicates an expected call of GetUserRolesAndAccess.
func (mr *MockUserManagementServiceMockRecorder) GetUserRolesAndAccess(ctx, schema, userID, scopeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRolesAndAccess", reflect.TypeOf((*MockUserManagementService)(nil).GetUserRolesAndAccess), ctx, schema, userID, scopeID)
}

// GetUsersWithRole mocks base method.
func (m *MockUserManagementService) GetUsersWithRole(ctx context.Context, schema string) ([]dto.UserWithRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersWithRole", ctx, schema)
	ret0, _ := ret[0].([]dto.UserWithRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersWithRole indicates an expected call of GetUsersWithRole.
func (mr *MockUserManagementServiceMockRecorder) GetUsersWithRole(ctx, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersWithRole", reflect.TypeOf((*MockUserManagementService)(nil).GetUsersWithRole), ctx, schema)
}

// GetWorkspaces mocks base method.
func (m *MockUserManagementService) GetWorkspaces(ctx context.Context, schema, userID, roles string) ([]dto.UserWorkspaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaces", ctx, schema, userID, roles)
	ret0, _ := ret[0].([]dto.UserWorkspaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaces indicates an expected call of GetWorkspaces.
func (mr *MockUserManagementServiceMockRecorder) GetWorkspaces(ctx, schema, userID, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaces", reflect.TypeOf((*MockUserManagementService)(nil).GetWorkspaces), ctx, schema, userID, roles)
}

// RemoveAvatar mocks base method.
func (m *MockUserManagementService) RemoveAvatar(ctx context.Context, schema, userID string) (dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAvatar", ctx, schema, userID)
	ret0, _ := ret[0].(dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveAvatar indicates an expected call of RemoveAvatar.
func (mr *MockUserManagementServiceMockRecorder) RemoveAvatar(ctx, schema, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAvatar", reflect.TypeOf((*MockUserManagementService)(nil).RemoveAvatar), ctx, schema, userID)
}

// UpdatePassword mocks base method.
func (m *MockUserManagementService) UpdatePassword(ctx context.Context, schema, userID string, updateData dto.UpdateUserPasswordRequest) (tenant.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, schema, userID, updateData)
	ret0, _ := ret[0].(tenant.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserManagementServiceMockRecorder) UpdatePassword(ctx, schema, userID, updateData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserManagementService)(nil).UpdatePassword), ctx, schema, userID, updateData)
}

// UpdateUser mocks base method.
func (m *MockUserManagementService) UpdateUser(ctx context.Context, schema, id string, updateData map[string]any) (tenant.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, schema, id, updateData)
	ret0, _ := ret[0].(tenant.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserManagementServiceMockRecorder) UpdateUser(ctx, schema, id, updateData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserManagementService)(nil).UpdateUser), ctx, schema, id, updateData)
}

// UpdateUserProfile mocks base method.
func (m *MockUserManagementService) UpdateUserProfile(ctx context.Context, schema, userID string, updateData dto.UpdateUserProfileRequest) (dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", ctx, schema, userID, updateData)
	ret0, _ := ret[0].(dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockUserManagementServiceMockRecorder) UpdateUserProfile(ctx, schema, userID, updateData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockUserManagementService)(nil).UpdateUserProfile), ctx, schema, userID, updateData)
}
