// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces/table_management.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/interfaces/table_management.go -destination=tests/handlers/mocks/mock_table_management.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"
	dto "serenibase/internal/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockTableManagementService is a mock of TableManagementService interface.
type MockTableManagementService struct {
	ctrl     *gomock.Controller
	recorder *MockTableManagementServiceMockRecorder
	isgomock struct{}
}

// MockTableManagementServiceMockRecorder is the mock recorder for MockTableManagementService.
type MockTableManagementServiceMockRecorder struct {
	mock *MockTableManagementService
}

// NewMockTableManagementService creates a new mock instance.
func NewMockTableManagementService(ctrl *gomock.Controller) *MockTableManagementService {
	mock := &MockTableManagementService{ctrl: ctrl}
	mock.recorder = &MockTableManagementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTableManagementService) EXPECT() *MockTableManagementServiceMockRecorder {
	return m.recorder
}

// AddAttachment mocks base method.
func (m *MockTableManagementService) AddAttachment(ctx context.Context, schemaName string, req dto.AddAttachmentRequest, files []*multipart.FileHeader) (dto.RecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAttachment", ctx, schemaName, req, files)
	ret0, _ := ret[0].(dto.RecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAttachment indicates an expected call of AddAttachment.
func (mr *MockTableManagementServiceMockRecorder) AddAttachment(ctx, schemaName, req, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAttachment", reflect.TypeOf((*MockTableManagementService)(nil).AddAttachment), ctx, schemaName, req, files)
}

// AddColumn mocks base method.
func (m *MockTableManagementService) AddColumn(ctx context.Context, schemaName string, columnData dto.AddColumnRequest) (dto.ColumnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddColumn", ctx, schemaName, columnData)
	ret0, _ := ret[0].(dto.ColumnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddColumn indicates an expected call of AddColumn.
func (mr *MockTableManagementServiceMockRecorder) AddColumn(ctx, schemaName, columnData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddColumn", reflect.TypeOf((*MockTableManagementService)(nil).AddColumn), ctx, schemaName, columnData)
}

// BulkDeleteRows mocks base method.
func (m *MockTableManagementService) BulkDeleteRows(ctx context.Context, schemaName string, req dto.BulkDeleteRowsRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkDeleteRows", ctx, schemaName, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkDeleteRows indicates an expected call of BulkDeleteRows.
func (mr *MockTableManagementServiceMockRecorder) BulkDeleteRows(ctx, schemaName, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkDeleteRows", reflect.TypeOf((*MockTableManagementService)(nil).BulkDeleteRows), ctx, schemaName, req)
}

// CreateRow mocks base method.
func (m *MockTableManagementService) CreateRow(ctx context.Context, schemaName string, req dto.CreateRowRequest) (dto.RecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRow", ctx, schemaName, req)
	ret0, _ := ret[0].(dto.RecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRow indicates an expected call of CreateRow.
func (mr *MockTableManagementServiceMockRecorder) CreateRow(ctx, schemaName, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRow", reflect.TypeOf((*MockTableManagementService)(nil).CreateRow), ctx, schemaName, req)
}

// CreateRowWithRecords mocks base method.
func (m *MockTableManagementService) CreateRowWithRecords(ctx context.Context, schemaName, modelAlias string, record map[string]any) (dto.RecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRowWithRecords", ctx, schemaName, modelAlias, record)
	ret0, _ := ret[0].(dto.RecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRowWithRecords indicates an expected call of CreateRowWithRecords.
func (mr *MockTableManagementServiceMockRecorder) CreateRowWithRecords(ctx, schemaName, modelAlias, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRowWithRecords", reflect.TypeOf((*MockTableManagementService)(nil).CreateRowWithRecords), ctx, schemaName, modelAlias, record)
}

// CreateRowsWithRecordsBulk mocks base method.
func (m *MockTableManagementService) CreateRowsWithRecordsBulk(ctx context.Context, schemaName, modelAlias string, records []map[string]any) ([]dto.RecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRowsWithRecordsBulk", ctx, schemaName, modelAlias, records)
	ret0, _ := ret[0].([]dto.RecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRowsWithRecordsBulk indicates an expected call of CreateRowsWithRecordsBulk.
func (mr *MockTableManagementServiceMockRecorder) CreateRowsWithRecordsBulk(ctx, schemaName, modelAlias, records any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRowsWithRecordsBulk", reflect.TypeOf((*MockTableManagementService)(nil).CreateRowsWithRecordsBulk), ctx, schemaName, modelAlias, records)
}

// CreateTableWithDefaults mocks base method.
func (m *MockTableManagementService) CreateTableWithDefaults(ctx context.Context, tableData dto.CreateTableRequest, schemaName string) (dto.TableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTableWithDefaults", ctx, tableData, schemaName)
	ret0, _ := ret[0].(dto.TableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTableWithDefaults indicates an expected call of CreateTableWithDefaults.
func (mr *MockTableManagementServiceMockRecorder) CreateTableWithDefaults(ctx, tableData, schemaName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTableWithDefaults", reflect.TypeOf((*MockTableManagementService)(nil).CreateTableWithDefaults), ctx, tableData, schemaName)
}

// CreateView mocks base method.
func (m *MockTableManagementService) CreateView(ctx context.Context, schemaName string, viewData dto.CreateViewRequest) (dto.ViewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateView", ctx, schemaName, viewData)
	ret0, _ := ret[0].(dto.ViewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateView indicates an expected call of CreateView.
func (mr *MockTableManagementServiceMockRecorder) CreateView(ctx, schemaName, viewData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateView", reflect.TypeOf((*MockTableManagementService)(nil).CreateView), ctx, schemaName, viewData)
}

// DeleteColumn mocks base method.
func (m *MockTableManagementService) DeleteColumn(ctx context.Context, schemaName, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteColumn", ctx, schemaName, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteColumn indicates an expected call of DeleteColumn.
func (mr *MockTableManagementServiceMockRecorder) DeleteColumn(ctx, schemaName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteColumn", reflect.TypeOf((*MockTableManagementService)(nil).DeleteColumn), ctx, schemaName, id)
}

// DeleteRow mocks base method.
func (m *MockTableManagementService) DeleteRow(ctx context.Context, schemaName string, req dto.DeleteRowDataRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRow", ctx, schemaName, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRow indicates an expected call of DeleteRow.
func (mr *MockTableManagementServiceMockRecorder) DeleteRow(ctx, schemaName, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRow", reflect.TypeOf((*MockTableManagementService)(nil).DeleteRow), ctx, schemaName, req)
}

// DeleteTable mocks base method.
func (m *MockTableManagementService) DeleteTable(ctx context.Context, schemaName, modelID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTable", ctx, schemaName, modelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTable indicates an expected call of DeleteTable.
func (mr *MockTableManagementServiceMockRecorder) DeleteTable(ctx, schemaName, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTable", reflect.TypeOf((*MockTableManagementService)(nil).DeleteTable), ctx, schemaName, modelID)
}

// DeleteView mocks base method.
func (m *MockTableManagementService) DeleteView(ctx context.Context, schemaName, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteView", ctx, schemaName, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteView indicates an expected call of DeleteView.
func (mr *MockTableManagementServiceMockRecorder) DeleteView(ctx, schemaName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteView", reflect.TypeOf((*MockTableManagementService)(nil).DeleteView), ctx, schemaName, id)
}

// GetAllColumns mocks base method.
func (m *MockTableManagementService) GetAllColumns(ctx context.Context, schemaName string) ([]dto.ColumnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllColumns", ctx, schemaName)
	ret0, _ := ret[0].([]dto.ColumnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllColumns indicates an expected call of GetAllColumns.
func (mr *MockTableManagementServiceMockRecorder) GetAllColumns(ctx, schemaName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllColumns", reflect.TypeOf((*MockTableManagementService)(nil).GetAllColumns), ctx, schemaName)
}

// GetAllRecords mocks base method.
func (m *MockTableManagementService) GetAllRecords(ctx context.Context, schemaName, modelID string) (dto.RecordsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRecords", ctx, schemaName, modelID)
	ret0, _ := ret[0].(dto.RecordsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRecords indicates an expected call of GetAllRecords.
func (mr *MockTableManagementServiceMockRecorder) GetAllRecords(ctx, schemaName, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRecords", reflect.TypeOf((*MockTableManagementService)(nil).GetAllRecords), ctx, schemaName, modelID)
}

// GetAllTables mocks base method.
func (m *MockTableManagementService) GetAllTables(ctx context.Context, schemaName string) ([]dto.TableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTables", ctx, schemaName)
	ret0, _ := ret[0].([]dto.TableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTables indicates an expected call of GetAllTables.
func (mr *MockTableManagementServiceMockRecorder) GetAllTables(ctx, schemaName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTables", reflect.TypeOf((*MockTableManagementService)(nil).GetAllTables), ctx, schemaName)
}

// GetAllViews mocks base method.
func (m *MockTableManagementService) GetAllViews(ctx context.Context, schemaName string) ([]dto.ViewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllViews", ctx, schemaName)
	ret0, _ := ret[0].([]dto.ViewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllViews indicates an expected call of GetAllViews.
func (mr *MockTableManagementServiceMockRecorder) GetAllViews(ctx, schemaName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllViews", reflect.TypeOf((*MockTableManagementService)(nil).GetAllViews), ctx, schemaName)
}

// GetColumnById mocks base method.
func (m *MockTableManagementService) GetColumnById(ctx context.Context, schemaName, id string) (dto.ColumnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetColumnById", ctx, schemaName, id)
	ret0, _ := ret[0].(dto.ColumnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetColumnById indicates an expected call of GetColumnById.
func (mr *MockTableManagementServiceMockRecorder) GetColumnById(ctx, schemaName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetColumnById", reflect.TypeOf((*MockTableManagementService)(nil).GetColumnById), ctx, schemaName, id)
}

// GetColumnsByModelID mocks base method.
func (m *MockTableManagementService) GetColumnsByModelID(ctx context.Context, schemaName, modelID string) ([]dto.ColumnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetColumnsByModelID", ctx, schemaName, modelID)
	ret0, _ := ret[0].([]dto.ColumnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetColumnsByModelID indicates an expected call of GetColumnsByModelID.
func (mr *MockTableManagementServiceMockRecorder) GetColumnsByModelID(ctx, schemaName, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetColumnsByModelID", reflect.TypeOf((*MockTableManagementService)(nil).GetColumnsByModelID), ctx, schemaName, modelID)
}

// GetModelByBaseID mocks base method.
func (m *MockTableManagementService) GetModelByBaseID(ctx context.Context, schemaName, baseID string) ([]dto.TableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelByBaseID", ctx, schemaName, baseID)
	ret0, _ := ret[0].([]dto.TableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelByBaseID indicates an expected call of GetModelByBaseID.
func (mr *MockTableManagementServiceMockRecorder) GetModelByBaseID(ctx, schemaName, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelByBaseID", reflect.TypeOf((*MockTableManagementService)(nil).GetModelByBaseID), ctx, schemaName, baseID)
}

// GetModelByWorkspaceID mocks base method.
func (m *MockTableManagementService) GetModelByWorkspaceID(ctx context.Context, schemaName, workspaceID string) ([]dto.TableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelByWorkspaceID", ctx, schemaName, workspaceID)
	ret0, _ := ret[0].([]dto.TableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelByWorkspaceID indicates an expected call of GetModelByWorkspaceID.
func (mr *MockTableManagementServiceMockRecorder) GetModelByWorkspaceID(ctx, schemaName, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelByWorkspaceID", reflect.TypeOf((*MockTableManagementService)(nil).GetModelByWorkspaceID), ctx, schemaName, workspaceID)
}

// GetTableByID mocks base method.
func (m *MockTableManagementService) GetTableByID(ctx context.Context, id, schemaName string) (dto.TableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTableByID", ctx, id, schemaName)
	ret0, _ := ret[0].(dto.TableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTableByID indicates an expected call of GetTableByID.
func (mr *MockTableManagementServiceMockRecorder) GetTableByID(ctx, id, schemaName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTableByID", reflect.TypeOf((*MockTableManagementService)(nil).GetTableByID), ctx, id, schemaName)
}

// GetViewByID mocks base method.
func (m *MockTableManagementService) GetViewByID(ctx context.Context, schemaName, id string) (dto.ViewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetViewByID", ctx, schemaName, id)
	ret0, _ := ret[0].(dto.ViewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetViewByID indicates an expected call of GetViewByID.
func (mr *MockTableManagementServiceMockRecorder) GetViewByID(ctx, schemaName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetViewByID", reflect.TypeOf((*MockTableManagementService)(nil).GetViewByID), ctx, schemaName, id)
}

// GetViewsByModelID mocks base method.
func (m *MockTableManagementService) GetViewsByModelID(ctx context.Context, schemaName, modelID string) ([]dto.ViewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetViewsByModelID", ctx, schemaName, modelID)
	ret0, _ := ret[0].([]dto.ViewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetViewsByModelID indicates an expected call of GetViewsByModelID.
func (mr *MockTableManagementServiceMockRecorder) GetViewsByModelID(ctx, schemaName, modelID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetViewsByModelID", reflect.TypeOf((*MockTableManagementService)(nil).GetViewsByModelID), ctx, schemaName, modelID)
}

// InsertRowData mocks base method.
func (m *MockTableManagementService) InsertRowData(ctx context.Context, schemaName string, req dto.InsertRowDataRequest) (dto.RecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRowData", ctx, schemaName, req)
	ret0, _ := ret[0].(dto.RecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertRowData indicates an expected call of InsertRowData.
func (mr *MockTableManagementServiceMockRecorder) InsertRowData(ctx, schemaName, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRowData", reflect.TypeOf((*MockTableManagementService)(nil).InsertRowData), ctx, schemaName, req)
}

// RemoveAttachments mocks base method.
func (m *MockTableManagementService) RemoveAttachments(ctx context.Context, schemaName string, req dto.RemoveAttachmentsRequest) (dto.RecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAttachments", ctx, schemaName, req)
	ret0, _ := ret[0].(dto.RecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveAttachments indicates an expected call of RemoveAttachments.
func (mr *MockTableManagementServiceMockRecorder) RemoveAttachments(ctx, schemaName, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAttachments", reflect.TypeOf((*MockTableManagementService)(nil).RemoveAttachments), ctx, schemaName, req)
}

// ReorderColumn mocks base method.
func (m *MockTableManagementService) ReorderColumn(ctx context.Context, schemaName string, req dto.ReorderColumnRequest) ([]dto.ColumnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderColumn", ctx, schemaName, req)
	ret0, _ := ret[0].([]dto.ColumnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReorderColumn indicates an expected call of ReorderColumn.
func (mr *MockTableManagementServiceMockRecorder) ReorderColumn(ctx, schemaName, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderColumn", reflect.TypeOf((*MockTableManagementService)(nil).ReorderColumn), ctx, schemaName, req)
}

// UpdateColumn mocks base method.
func (m *MockTableManagementService) UpdateColumn(ctx context.Context, schemaName, id string, req dto.ColumnUpdate) (dto.ColumnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateColumn", ctx, schemaName, id, req)
	ret0, _ := ret[0].(dto.ColumnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateColumn indicates an expected call of UpdateColumn.
func (mr *MockTableManagementServiceMockRecorder) UpdateColumn(ctx, schemaName, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateColumn", reflect.TypeOf((*MockTableManagementService)(nil).UpdateColumn), ctx, schemaName, id, req)
}

// UpdateRawDataForLinks mocks base method.
func (m *MockTableManagementService) UpdateRawDataForLinks(ctx context.Context, schemaName string, req dto.UpdateRowDataLinksRequest) (dto.RecordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRawDataForLinks", ctx, schemaName, req)
	ret0, _ := ret[0].(dto.RecordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRawDataForLinks indicates an expected call of UpdateRawDataForLinks.
func (mr *MockTableManagementServiceMockRecorder) UpdateRawDataForLinks(ctx, schemaName, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRawDataForLinks", reflect.TypeOf((*MockTableManagementService)(nil).UpdateRawDataForLinks), ctx, schemaName, req)
}

// UpdateTable mocks base method.
func (m *MockTableManagementService) UpdateTable(ctx context.Context, id string, tableData dto.UpdateTableRequest, schemaName string) (dto.TableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTable", ctx, id, tableData, schemaName)
	ret0, _ := ret[0].(dto.TableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTable indicates an expected call of UpdateTable.
func (mr *MockTableManagementServiceMockRecorder) UpdateTable(ctx, id, tableData, schemaName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTable", reflect.TypeOf((*MockTableManagementService)(nil).UpdateTable), ctx, id, tableData, schemaName)
}

// UpdateView mocks base method.
func (m *MockTableManagementService) UpdateView(ctx context.Context, schemaName, id string, req dto.ViewUpdate) (dto.ViewResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateView", ctx, schemaName, id, req)
	ret0, _ := ret[0].(dto.ViewResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateView indicates an expected call of UpdateView.
func (mr *MockTableManagementServiceMockRecorder) UpdateView(ctx, schemaName, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateView", reflect.TypeOf((*MockTableManagementService)(nil).UpdateView), ctx, schemaName, id, req)
}
