// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces/base_management.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/interfaces/base_management.go -destination=tests/handlers/mocks/mock_base_management.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"
	dto "serenibase/internal/dto"
	tenant "serenibase/internal/models/tenant"

	gomock "go.uber.org/mock/gomock"
)

// MockBaseManagementService is a mock of BaseManagementService interface.
type MockBaseManagementService struct {
	ctrl     *gomock.Controller
	recorder *MockBaseManagementServiceMockRecorder
	isgomock struct{}
}

// MockBaseManagementServiceMockRecorder is the mock recorder for MockBaseManagementService.
type MockBaseManagementServiceMockRecorder struct {
	mock *MockBaseManagementService
}

// NewMockBaseManagementService creates a new mock instance.
func NewMockBaseManagementService(ctrl *gomock.Controller) *MockBaseManagementService {
	mock := &MockBaseManagementService{ctrl: ctrl}
	mock.recorder = &MockBaseManagementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseManagementService) EXPECT() *MockBaseManagementServiceMockRecorder {
	return m.recorder
}

// AddBaseImage mocks base method.
func (m *MockBaseManagementService) AddBaseImage(ctx context.Context, schema, baseID string, fileHeader *multipart.FileHeader, userId string) (tenant.Base, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBaseImage", ctx, schema, baseID, fileHeader, userId)
	ret0, _ := ret[0].(tenant.Base)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddBaseImage indicates an expected call of AddBaseImage.
func (mr *MockBaseManagementServiceMockRecorder) AddBaseImage(ctx, schema, baseID, fileHeader, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBaseImage", reflect.TypeOf((*MockBaseManagementService)(nil).AddBaseImage), ctx, schema, baseID, fileHeader, userId)
}

// CreateBase mocks base method.
func (m *MockBaseManagementService) CreateBase(ctx context.Context, req dto.CreateBaseRequest, schemaName, userId string) (tenant.Base, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBase", ctx, req, schemaName, userId)
	ret0, _ := ret[0].(tenant.Base)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBase indicates an expected call of CreateBase.
func (mr *MockBaseManagementServiceMockRecorder) CreateBase(ctx, req, schemaName, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBase", reflect.TypeOf((*MockBaseManagementService)(nil).CreateBase), ctx, req, schemaName, userId)
}

// CreateBaseWithImage mocks base method.
func (m *MockBaseManagementService) CreateBaseWithImage(ctx context.Context, req dto.CreateBaseRequest, schemaName, userId string, fileHeader *multipart.FileHeader) (tenant.Base, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBaseWithImage", ctx, req, schemaName, userId, fileHeader)
	ret0, _ := ret[0].(tenant.Base)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBaseWithImage indicates an expected call of CreateBaseWithImage.
func (mr *MockBaseManagementServiceMockRecorder) CreateBaseWithImage(ctx, req, schemaName, userId, fileHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBaseWithImage", reflect.TypeOf((*MockBaseManagementService)(nil).CreateBaseWithImage), ctx, req, schemaName, userId, fileHeader)
}

// DeleteBase mocks base method.
func (m *MockBaseManagementService) DeleteBase(ctx context.Context, schemaName, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBase", ctx, schemaName, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBase indicates an expected call of DeleteBase.
func (mr *MockBaseManagementServiceMockRecorder) DeleteBase(ctx, schemaName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBase", reflect.TypeOf((*MockBaseManagementService)(nil).DeleteBase), ctx, schemaName, id)
}

// GetAllBasesWithAccess mocks base method.
func (m *MockBaseManagementService) GetAllBasesWithAccess(ctx context.Context, schemaName string, workspaceMemberData *tenant.WorkspaceMember) ([]tenant.Base, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBasesWithAccess", ctx, schemaName, workspaceMemberData)
	ret0, _ := ret[0].([]tenant.Base)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBasesWithAccess indicates an expected call of GetAllBasesWithAccess.
func (mr *MockBaseManagementServiceMockRecorder) GetAllBasesWithAccess(ctx, schemaName, workspaceMemberData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBasesWithAccess", reflect.TypeOf((*MockBaseManagementService)(nil).GetAllBasesWithAccess), ctx, schemaName, workspaceMemberData)
}

// GetBaseByID mocks base method.
func (m *MockBaseManagementService) GetBaseByID(ctx context.Context, schemaName, id string) (tenant.Base, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseByID", ctx, schemaName, id)
	ret0, _ := ret[0].(tenant.Base)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBaseByID indicates an expected call of GetBaseByID.
func (mr *MockBaseManagementServiceMockRecorder) GetBaseByID(ctx, schemaName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseByID", reflect.TypeOf((*MockBaseManagementService)(nil).GetBaseByID), ctx, schemaName, id)
}

// GetBasesByWorkspace mocks base method.
func (m *MockBaseManagementService) GetBasesByWorkspace(ctx context.Context, schemaName, workspaceID string) ([]tenant.Base, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasesByWorkspace", ctx, schemaName, workspaceID)
	ret0, _ := ret[0].([]tenant.Base)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasesByWorkspace indicates an expected call of GetBasesByWorkspace.
func (mr *MockBaseManagementServiceMockRecorder) GetBasesByWorkspace(ctx, schemaName, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasesByWorkspace", reflect.TypeOf((*MockBaseManagementService)(nil).GetBasesByWorkspace), ctx, schemaName, workspaceID)
}

// GetTablesByBaseId mocks base method.
func (m *MockBaseManagementService) GetTablesByBaseId(ctx context.Context, schemaName, baseID string) ([]dto.TableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTablesByBaseId", ctx, schemaName, baseID)
	ret0, _ := ret[0].([]dto.TableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTablesByBaseId indicates an expected call of GetTablesByBaseId.
func (mr *MockBaseManagementServiceMockRecorder) GetTablesByBaseId(ctx, schemaName, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTablesByBaseId", reflect.TypeOf((*MockBaseManagementService)(nil).GetTablesByBaseId), ctx, schemaName, baseID)
}

// RemoveBaseImage mocks base method.
func (m *MockBaseManagementService) RemoveBaseImage(ctx context.Context, schema, baseID, userId string) (tenant.Base, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBaseImage", ctx, schema, baseID, userId)
	ret0, _ := ret[0].(tenant.Base)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveBaseImage indicates an expected call of RemoveBaseImage.
func (mr *MockBaseManagementServiceMockRecorder) RemoveBaseImage(ctx, schema, baseID, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBaseImage", reflect.TypeOf((*MockBaseManagementService)(nil).RemoveBaseImage), ctx, schema, baseID, userId)
}

// RemoveUserFromBase mocks base method.
func (m *MockBaseManagementService) RemoveUserFromBase(ctx context.Context, schemaName, baseID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromBase", ctx, schemaName, baseID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromBase indicates an expected call of RemoveUserFromBase.
func (mr *MockBaseManagementServiceMockRecorder) RemoveUserFromBase(ctx, schemaName, baseID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromBase", reflect.TypeOf((*MockBaseManagementService)(nil).RemoveUserFromBase), ctx, schemaName, baseID, userID)
}

// UpdateBase mocks base method.
func (m *MockBaseManagementService) UpdateBase(ctx context.Context, schemaName, id string, req dto.BaseUpdate, userId string) (tenant.Base, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBase", ctx, schemaName, id, req, userId)
	ret0, _ := ret[0].(tenant.Base)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBase indicates an expected call of UpdateBase.
func (mr *MockBaseManagementServiceMockRecorder) UpdateBase(ctx, schemaName, id, req, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBase", reflect.TypeOf((*MockBaseManagementService)(nil).UpdateBase), ctx, schemaName, id, req, userId)
}
