// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces/asset_management.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/interfaces/asset_management.go -destination=tests/handlers/mocks/mock_asset_management.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "serenibase/internal/dto"
	tenant "serenibase/internal/models/tenant"

	gomock "go.uber.org/mock/gomock"
)

// MockAssetManagementService is a mock of AssetManagementService interface.
type MockAssetManagementService struct {
	ctrl     *gomock.Controller
	recorder *MockAssetManagementServiceMockRecorder
	isgomock struct{}
}

// MockAssetManagementServiceMockRecorder is the mock recorder for MockAssetManagementService.
type MockAssetManagementServiceMockRecorder struct {
	mock *MockAssetManagementService
}

// NewMockAssetManagementService creates a new mock instance.
func NewMockAssetManagementService(ctrl *gomock.Controller) *MockAssetManagementService {
	mock := &MockAssetManagementService{ctrl: ctrl}
	mock.recorder = &MockAssetManagementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssetManagementService) EXPECT() *MockAssetManagementServiceMockRecorder {
	return m.recorder
}

// DeleteAsset mocks base method.
func (m *MockAssetManagementService) DeleteAsset(ctx context.Context, assetId, schemaName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAsset", ctx, assetId, schemaName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAsset indicates an expected call of DeleteAsset.
func (mr *MockAssetManagementServiceMockRecorder) DeleteAsset(ctx, assetId, schemaName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAsset", reflect.TypeOf((*MockAssetManagementService)(nil).DeleteAsset), ctx, assetId, schemaName)
}

// GetAssetByURL mocks base method.
func (m *MockAssetManagementService) GetAssetByURL(ctx context.Context, schemaName, url string) (tenant.Assets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssetByURL", ctx, schemaName, url)
	ret0, _ := ret[0].(tenant.Assets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssetByURL indicates an expected call of GetAssetByURL.
func (mr *MockAssetManagementServiceMockRecorder) GetAssetByURL(ctx, schemaName, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssetByURL", reflect.TypeOf((*MockAssetManagementService)(nil).GetAssetByURL), ctx, schemaName, url)
}

// GetBulkAssets mocks base method.
func (m *MockAssetManagementService) GetBulkAssets(ctx context.Context, schemaName string, ids []string) ([]tenant.Assets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBulkAssets", ctx, schemaName, ids)
	ret0, _ := ret[0].([]tenant.Assets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBulkAssets indicates an expected call of GetBulkAssets.
func (mr *MockAssetManagementServiceMockRecorder) GetBulkAssets(ctx, schemaName, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBulkAssets", reflect.TypeOf((*MockAssetManagementService)(nil).GetBulkAssets), ctx, schemaName, ids)
}

// UpdateAsset mocks base method.
func (m *MockAssetManagementService) UpdateAsset(ctx context.Context, assetId string, assetData dto.AssetUpdate, schemaName string) (tenant.Assets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAsset", ctx, assetId, assetData, schemaName)
	ret0, _ := ret[0].(tenant.Assets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAsset indicates an expected call of UpdateAsset.
func (mr *MockAssetManagementServiceMockRecorder) UpdateAsset(ctx, assetId, assetData, schemaName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAsset", reflect.TypeOf((*MockAssetManagementService)(nil).UpdateAsset), ctx, assetId, assetData, schemaName)
}

// Upload mocks base method.
func (m *MockAssetManagementService) Upload(ctx context.Context, req dto.UploadAssetRequest, schema string) ([]tenant.Assets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, req, schema)
	ret0, _ := ret[0].([]tenant.Assets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAssetManagementServiceMockRecorder) Upload(ctx, req, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAssetManagementService)(nil).Upload), ctx, req, schema)
}

// UploadImage mocks base method.
func (m *MockAssetManagementService) UploadImage(ctx context.Context, req dto.UploadAssetRequest, schema string) ([]tenant.Assets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, req, schema)
	ret0, _ := ret[0].([]tenant.Assets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockAssetManagementServiceMockRecorder) UploadImage(ctx, req, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockAssetManagementService)(nil).UploadImage), ctx, req, schema)
}
