// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces/organization.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/interfaces/organization.go -destination=tests/handlers/mocks/mock_organization_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "github.com/aptlogica/sereni-base/internal/dto"
	tenant "github.com/aptlogica/sereni-base/internal/models/tenant"

	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationService is a mock of OrganizationService interface.
type MockOrganizationService struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationServiceMockRecorder
	isgomock struct{}
}

// MockOrganizationServiceMockRecorder is the mock recorder for MockOrganizationService.
type MockOrganizationServiceMockRecorder struct {
	mock *MockOrganizationService
}

// NewMockOrganizationService creates a new mock instance.
func NewMockOrganizationService(ctrl *gomock.Controller) *MockOrganizationService {
	mock := &MockOrganizationService{ctrl: ctrl}
	mock.recorder = &MockOrganizationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationService) EXPECT() *MockOrganizationServiceMockRecorder {
	return m.recorder
}

// CreateOrganization mocks base method.
func (m *MockOrganizationService) CreateOrganization(ctx context.Context, schemaName string, req dto.CreateOrganizationRequest) (tenant.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, schemaName, req)
	ret0, _ := ret[0].(tenant.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockOrganizationServiceMockRecorder) CreateOrganization(ctx, schemaName, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockOrganizationService)(nil).CreateOrganization), ctx, schemaName, req)
}

// DeleteOrganization mocks base method.
func (m *MockOrganizationService) DeleteOrganization(ctx context.Context, schemaName, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrganization", ctx, schemaName, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrganization indicates an expected call of DeleteOrganization.
func (mr *MockOrganizationServiceMockRecorder) DeleteOrganization(ctx, schemaName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganization", reflect.TypeOf((*MockOrganizationService)(nil).DeleteOrganization), ctx, schemaName, id)
}

// GetOrganization mocks base method.
func (m *MockOrganizationService) GetOrganization(ctx context.Context, schemaName string) (tenant.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganization", ctx, schemaName)
	ret0, _ := ret[0].(tenant.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganization indicates an expected call of GetOrganization.
func (mr *MockOrganizationServiceMockRecorder) GetOrganization(ctx, schemaName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganization", reflect.TypeOf((*MockOrganizationService)(nil).GetOrganization), ctx, schemaName)
}

// GetOrganizationByEmail mocks base method.
func (m *MockOrganizationService) GetOrganizationByEmail(ctx context.Context, schemaName, email string) (tenant.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationByEmail", ctx, schemaName, email)
	ret0, _ := ret[0].(tenant.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationByEmail indicates an expected call of GetOrganizationByEmail.
func (mr *MockOrganizationServiceMockRecorder) GetOrganizationByEmail(ctx, schemaName, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationByEmail", reflect.TypeOf((*MockOrganizationService)(nil).GetOrganizationByEmail), ctx, schemaName, email)
}

// GetOrganizationByID mocks base method.
func (m *MockOrganizationService) GetOrganizationByID(ctx context.Context, schemaName, id string) (tenant.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationByID", ctx, schemaName, id)
	ret0, _ := ret[0].(tenant.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationByID indicates an expected call of GetOrganizationByID.
func (mr *MockOrganizationServiceMockRecorder) GetOrganizationByID(ctx, schemaName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationByID", reflect.TypeOf((*MockOrganizationService)(nil).GetOrganizationByID), ctx, schemaName, id)
}

// UpdateOrganization mocks base method.
func (m *MockOrganizationService) UpdateOrganization(ctx context.Context, schemaName, id string, req dto.UpdateOrganizationRequest) (tenant.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrganization", ctx, schemaName, id, req)
	ret0, _ := ret[0].(tenant.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganization indicates an expected call of UpdateOrganization.
func (mr *MockOrganizationServiceMockRecorder) UpdateOrganization(ctx, schemaName, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganization", reflect.TypeOf((*MockOrganizationService)(nil).UpdateOrganization), ctx, schemaName, id, req)
}
