// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces/workspace_management.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/interfaces/workspace_management.go -destination=tests/handlers/mocks/mock_workspace_management.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	dto "github.com/aptlogica/sereni-base/internal/dto"
	tenant "github.com/aptlogica/sereni-base/internal/models/tenant"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkspaceManagementService is a mock of WorkspaceManagementService interface.
type MockWorkspaceManagementService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceManagementServiceMockRecorder
	isgomock struct{}
}

// MockWorkspaceManagementServiceMockRecorder is the mock recorder for MockWorkspaceManagementService.
type MockWorkspaceManagementServiceMockRecorder struct {
	mock *MockWorkspaceManagementService
}

// NewMockWorkspaceManagementService creates a new mock instance.
func NewMockWorkspaceManagementService(ctrl *gomock.Controller) *MockWorkspaceManagementService {
	mock := &MockWorkspaceManagementService{ctrl: ctrl}
	mock.recorder = &MockWorkspaceManagementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceManagementService) EXPECT() *MockWorkspaceManagementServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkspaceManagementService) Create(ctx context.Context, req dto.CreateWorkspaceRequest, schemaName, userId string) (dto.WorkspaceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req, schemaName, userId)
	ret0, _ := ret[0].(dto.WorkspaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkspaceManagementServiceMockRecorder) Create(ctx, req, schemaName, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkspaceManagementService)(nil).Create), ctx, req, schemaName, userId)
}

// Delete mocks base method.
func (m *MockWorkspaceManagementService) Delete(ctx context.Context, schemaName, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, schemaName, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkspaceManagementServiceMockRecorder) Delete(ctx, schemaName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkspaceManagementService)(nil).Delete), ctx, schemaName, id)
}

// DeleteUserMappings mocks base method.
func (m *MockWorkspaceManagementService) DeleteUserMappings(ctx context.Context, schemaName, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserMappings", ctx, schemaName, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserMappings indicates an expected call of DeleteUserMappings.
func (mr *MockWorkspaceManagementServiceMockRecorder) DeleteUserMappings(ctx, schemaName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserMappings", reflect.TypeOf((*MockWorkspaceManagementService)(nil).DeleteUserMappings), ctx, schemaName, userID)
}

// GetAll mocks base method.
func (m *MockWorkspaceManagementService) GetAll(ctx context.Context, schemaName string) ([]tenant.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, schemaName)
	ret0, _ := ret[0].([]tenant.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockWorkspaceManagementServiceMockRecorder) GetAll(ctx, schemaName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockWorkspaceManagementService)(nil).GetAll), ctx, schemaName)
}

// GetAllBasesByWorkspaceId mocks base method.
func (m *MockWorkspaceManagementService) GetAllBasesByWorkspaceId(ctx context.Context, schemaName, workspaceID, role, userID string) ([]dto.BaseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBasesByWorkspaceId", ctx, schemaName, workspaceID, role, userID)
	ret0, _ := ret[0].([]dto.BaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBasesByWorkspaceId indicates an expected call of GetAllBasesByWorkspaceId.
func (mr *MockWorkspaceManagementServiceMockRecorder) GetAllBasesByWorkspaceId(ctx, schemaName, workspaceID, role, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBasesByWorkspaceId", reflect.TypeOf((*MockWorkspaceManagementService)(nil).GetAllBasesByWorkspaceId), ctx, schemaName, workspaceID, role, userID)
}

// GetBasesByWorkspaceId mocks base method.
func (m *MockWorkspaceManagementService) GetBasesByWorkspaceId(ctx context.Context, schemaName string, workspaceMemberData *tenant.WorkspaceMember) ([]tenant.Base, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasesByWorkspaceId", ctx, schemaName, workspaceMemberData)
	ret0, _ := ret[0].([]tenant.Base)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasesByWorkspaceId indicates an expected call of GetBasesByWorkspaceId.
func (mr *MockWorkspaceManagementServiceMockRecorder) GetBasesByWorkspaceId(ctx, schemaName, workspaceMemberData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasesByWorkspaceId", reflect.TypeOf((*MockWorkspaceManagementService)(nil).GetBasesByWorkspaceId), ctx, schemaName, workspaceMemberData)
}

// GetBulkWorkspaces mocks base method.
func (m *MockWorkspaceManagementService) GetBulkWorkspaces(ctx context.Context, schemaName string, workspaceIDs []string) ([]tenant.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBulkWorkspaces", ctx, schemaName, workspaceIDs)
	ret0, _ := ret[0].([]tenant.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBulkWorkspaces indicates an expected call of GetBulkWorkspaces.
func (mr *MockWorkspaceManagementServiceMockRecorder) GetBulkWorkspaces(ctx, schemaName, workspaceIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBulkWorkspaces", reflect.TypeOf((*MockWorkspaceManagementService)(nil).GetBulkWorkspaces), ctx, schemaName, workspaceIDs)
}

// GetByID mocks base method.
func (m *MockWorkspaceManagementService) GetByID(ctx context.Context, schemaName, id string) (tenant.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, schemaName, id)
	ret0, _ := ret[0].(tenant.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockWorkspaceManagementServiceMockRecorder) GetByID(ctx, schemaName, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWorkspaceManagementService)(nil).GetByID), ctx, schemaName, id)
}

// GetTablesByWorkspaceId mocks base method.
func (m *MockWorkspaceManagementService) GetTablesByWorkspaceId(ctx context.Context, schemaName, workspaceID string) ([]dto.TableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTablesByWorkspaceId", ctx, schemaName, workspaceID)
	ret0, _ := ret[0].([]dto.TableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTablesByWorkspaceId indicates an expected call of GetTablesByWorkspaceId.
func (mr *MockWorkspaceManagementServiceMockRecorder) GetTablesByWorkspaceId(ctx, schemaName, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTablesByWorkspaceId", reflect.TypeOf((*MockWorkspaceManagementService)(nil).GetTablesByWorkspaceId), ctx, schemaName, workspaceID)
}

// GetWorkspaceBaseMembers mocks base method.
func (m *MockWorkspaceManagementService) GetWorkspaceBaseMembers(ctx context.Context, schemaName, baseID string) ([]tenant.WorkspaceMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceBaseMembers", ctx, schemaName, baseID)
	ret0, _ := ret[0].([]tenant.WorkspaceMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceBaseMembers indicates an expected call of GetWorkspaceBaseMembers.
func (mr *MockWorkspaceManagementServiceMockRecorder) GetWorkspaceBaseMembers(ctx, schemaName, baseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceBaseMembers", reflect.TypeOf((*MockWorkspaceManagementService)(nil).GetWorkspaceBaseMembers), ctx, schemaName, baseID)
}

// GetWorkspaceMemberByUser mocks base method.
func (m *MockWorkspaceManagementService) GetWorkspaceMemberByUser(ctx context.Context, schemaName, userID string) ([]tenant.WorkspaceMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceMemberByUser", ctx, schemaName, userID)
	ret0, _ := ret[0].([]tenant.WorkspaceMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceMemberByUser indicates an expected call of GetWorkspaceMemberByUser.
func (mr *MockWorkspaceManagementServiceMockRecorder) GetWorkspaceMemberByUser(ctx, schemaName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceMemberByUser", reflect.TypeOf((*MockWorkspaceManagementService)(nil).GetWorkspaceMemberByUser), ctx, schemaName, userID)
}

// GetWorkspaceMembers mocks base method.
func (m *MockWorkspaceManagementService) GetWorkspaceMembers(ctx context.Context, schemaName, workspaceID string) ([]tenant.WorkspaceMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkspaceMembers", ctx, schemaName, workspaceID)
	ret0, _ := ret[0].([]tenant.WorkspaceMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkspaceMembers indicates an expected call of GetWorkspaceMembers.
func (mr *MockWorkspaceManagementServiceMockRecorder) GetWorkspaceMembers(ctx, schemaName, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkspaceMembers", reflect.TypeOf((*MockWorkspaceManagementService)(nil).GetWorkspaceMembers), ctx, schemaName, workspaceID)
}

// RemoveUserFromWorkspace mocks base method.
func (m *MockWorkspaceManagementService) RemoveUserFromWorkspace(ctx context.Context, schemaName, workspaceID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromWorkspace", ctx, schemaName, workspaceID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromWorkspace indicates an expected call of RemoveUserFromWorkspace.
func (mr *MockWorkspaceManagementServiceMockRecorder) RemoveUserFromWorkspace(ctx, schemaName, workspaceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromWorkspace", reflect.TypeOf((*MockWorkspaceManagementService)(nil).RemoveUserFromWorkspace), ctx, schemaName, workspaceID, userID)
}

// Update mocks base method.
func (m *MockWorkspaceManagementService) Update(ctx context.Context, schemaName, id string, req dto.WorkspaceUpdate, userId string) (tenant.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, schemaName, id, req, userId)
	ret0, _ := ret[0].(tenant.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWorkspaceManagementServiceMockRecorder) Update(ctx, schemaName, id, req, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkspaceManagementService)(nil).Update), ctx, schemaName, id, req, userId)
}

// UpdateWorkspaceMemberBases mocks base method.
func (m *MockWorkspaceManagementService) UpdateWorkspaceMemberBases(ctx context.Context, schemaName, workspaceID, userID, accessLevel, basesIds string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkspaceMemberBases", ctx, schemaName, workspaceID, userID, accessLevel, basesIds)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkspaceMemberBases indicates an expected call of UpdateWorkspaceMemberBases.
func (mr *MockWorkspaceManagementServiceMockRecorder) UpdateWorkspaceMemberBases(ctx, schemaName, workspaceID, userID, accessLevel, basesIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkspaceMemberBases", reflect.TypeOf((*MockWorkspaceManagementService)(nil).UpdateWorkspaceMemberBases), ctx, schemaName, workspaceID, userID, accessLevel, basesIds)
}
