// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/interfaces/import_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/interfaces/import_service.go -destination=tests/handlers/mocks/mock_import_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"
	dto "serenibase/internal/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockImportService is a mock of ImportService interface.
type MockImportService struct {
	ctrl     *gomock.Controller
	recorder *MockImportServiceMockRecorder
	isgomock struct{}
}

// MockImportServiceMockRecorder is the mock recorder for MockImportService.
type MockImportServiceMockRecorder struct {
	mock *MockImportService
}

// NewMockImportService creates a new mock instance.
func NewMockImportService(ctrl *gomock.Controller) *MockImportService {
	mock := &MockImportService{ctrl: ctrl}
	mock.recorder = &MockImportServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImportService) EXPECT() *MockImportServiceMockRecorder {
	return m.recorder
}

// Import mocks base method.
func (m *MockImportService) Import(ctx context.Context, schemaName string, req dto.CreateTableRequest, file *multipart.FileHeader) (dto.ImportTableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", ctx, schemaName, req, file)
	ret0, _ := ret[0].(dto.ImportTableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockImportServiceMockRecorder) Import(ctx, schemaName, req, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockImportService)(nil).Import), ctx, schemaName, req, file)
}
