package auth

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	appErrors "serenibase/internal/app-errors"
	"serenibase/internal/config"
	"serenibase/internal/models/tenant"

	"github.com/golang-jwt/jwt/v5"
)

const (
	contentTypeHeader  = "Content-Type"
	contentTypeJSON    = "application/json"
	errMarshalRequest  = "failed to marshal request: %w"
	errCreateRequest   = "failed to create request: %w"
	errCallAuthService = "failed to call auth-service: %w"
	errDecodeResponse  = "failed to decode response: %w"
)

func NewAuthProvider(cfg *config.AuthConfig) (AuthProvider, error) {
	return &AuthProviderService{
		AuthConfig: cfg,
		httpClient: &http.Client{
			Timeout: 10 * time.Second,
		},
	}, nil
}

type AuthProviderService struct {
	AuthConfig *config.AuthConfig
	httpClient *http.Client
}

// Request/Response models matching auth-service API (from swagger docs)
type authServiceRegisterRequest struct {
	Email    string   `json:"email"`
	Password string   `json:"password"`
	Roles    []string `json:"roles,omitempty"`
}

type authServiceLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type authServiceTokenResponse struct {
	Success bool   `json:"success"`
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
		TokenType    string `json:"token_type"`
		ExpiresIn    int64  `json:"expires_in"`
	} `json:"data"`
}

type authServiceValidateRequest struct {
	Token string `json:"token"`
}

type authServiceValidateResponse struct {
	Success bool   `json:"success"`
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    struct {
		UserID    string   `json:"sub"`
		Email     string   `json:"email"`
		Roles     []string `json:"roles"`
		TokenType string   `json:"token_type"`
		Issuer    string   `json:"iss"`
		ExpiresAt int64    `json:"exp"`
		IssuedAt  int64    `json:"iat"`
		NotBefore int64    `json:"nbf"`
	} `json:"data"`
}

type authServiceRefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type authServiceVerifyRequest struct {
	Token string `json:"token"`
}

type authServiceVerifyResponse struct {
	Success bool            `json:"success"`
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Data    map[string]bool `json:"data"`
}

// Custom Claims structure (kept for compatibility - used for locally generated tokens)
type CustomClaims struct {
	UserId        string `json:"user_id"`
	Email         string `json:"email"`
	Roles         string `json:"roles,omitempty"`
	EmailVerified bool   `json:"email_verified"`
	jwt.RegisteredClaims
}

// JWT Service Claims structure (for tokens generated by JWT service)
type JWTServiceClaims struct {
	Sub       string   `json:"sub"` // User ID
	Email     string   `json:"email"`
	Roles     []string `json:"roles"`      // Array of roles
	TokenType string   `json:"token_type"` // "access" or "refresh"
	jwt.RegisteredClaims
}

func (a *AuthProviderService) GenerateToken(ctx context.Context, user tenant.User) (Tokens, error) {
	// Generate tokens locally since auth-service requires password and may not have user synced
	// This is the pragmatic solution until we implement user synchronization or a service-to-service endpoint
	now := time.Now()

	// Create Access Token
	accessClaims := CustomClaims{
		UserId:        user.ID.String(),
		Email:         user.Email,
		EmailVerified: user.EmailVerified,
		Roles:         user.Roles,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(now.Add(time.Duration(a.AuthConfig.JWT.AccessTokenExpiry) * time.Second)),
			IssuedAt:  jwt.NewNumericDate(now),
			Issuer:    a.AuthConfig.JWT.Issuer,
		},
	}

	accessToken := jwt.NewWithClaims(jwt.SigningMethodHS256, accessClaims)
	signedAccessToken, err := accessToken.SignedString([]byte(a.AuthConfig.JWT.Secret))
	if err != nil {
		return Tokens{}, fmt.Errorf("failed to sign access token: %w", err)
	}

	// Create Refresh Token
	refreshClaims := CustomClaims{
		UserId:        user.ID.String(),
		Email:         user.Email,
		Roles:         user.Roles,
		EmailVerified: user.EmailVerified,
		RegisteredClaims: jwt.RegisteredClaims{
			ExpiresAt: jwt.NewNumericDate(now.Add(time.Duration(a.AuthConfig.JWT.RefreshTokenExpiry) * time.Second)),
			IssuedAt:  jwt.NewNumericDate(now),
			Issuer:    a.AuthConfig.JWT.Issuer,
		},
	}
	refreshToken := jwt.NewWithClaims(jwt.SigningMethodHS256, refreshClaims)
	signedRefreshToken, err := refreshToken.SignedString([]byte(a.AuthConfig.JWT.Secret))
	if err != nil {
		return Tokens{}, fmt.Errorf("failed to sign refresh token: %w", err)
	}

	return Tokens{
		AccessToken:  signedAccessToken,
		RefreshToken: signedRefreshToken,
	}, nil
}

func (a *AuthProviderService) ValidateToken(ctx context.Context, tokenStr string) (Claims, error) {
	// Remove "Bearer " prefix if present
	if len(tokenStr) > 7 && tokenStr[:7] == "Bearer " {
		tokenStr = tokenStr[7:]
	}

	// Try JWT service validation first
	reqBody := authServiceValidateRequest{
		Token: tokenStr,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return Claims{}, fmt.Errorf(errMarshalRequest, err)
	}

	url := fmt.Sprintf("%s/auth/validate-token", a.AuthConfig.URL)
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return Claims{}, fmt.Errorf(errCreateRequest, err)
	}

	req.Header.Set(contentTypeHeader, contentTypeJSON)

	resp, err := a.httpClient.Do(req)
	if err != nil {
		return Claims{}, fmt.Errorf(errCallAuthService, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return Claims{}, appErrors.TokenInvalid
	}

	var validateResp authServiceValidateResponse
	if err := json.NewDecoder(resp.Body).Decode(&validateResp); err != nil {
		return Claims{}, fmt.Errorf(errDecodeResponse, err)
	}

	if !validateResp.Success {
		return Claims{}, appErrors.TokenInvalid
	}

	// Parse the token to extract user_id (sub claim)
	// JWT service validate endpoint doesn't return the sub field, so we need to decode it ourselves
	token, err := jwt.ParseWithClaims(tokenStr, &JWTServiceClaims{}, func(token *jwt.Token) (interface{}, error) {
		if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, jwt.ErrSignatureInvalid
		}
		return []byte(a.AuthConfig.JWT.Secret), nil
	})

	if err != nil {
		return Claims{}, fmt.Errorf("failed to parse token: %w", err)
	}

	claims, ok := token.Claims.(*JWTServiceClaims)
	if !ok || !token.Valid {
		return Claims{}, appErrors.TokenInvalid
	}

	// Convert roles array to comma-separated string
	rolesStr := ""
	if len(claims.Roles) > 0 {
		for i, role := range claims.Roles {
			if i > 0 {
				rolesStr += ","
			}
			rolesStr += role
		}
	}

	return Claims{
		UserId: claims.Sub, // User ID from sub claim
		Roles:  rolesStr,   // Roles from token claims
	}, nil
}

func (a *AuthProviderService) RefreshToken(ctx context.Context, tokenStr string) (Tokens, error) {
	// Call auth-service /auth/refresh endpoint
	reqBody := authServiceRefreshRequest{
		RefreshToken: tokenStr,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return Tokens{}, fmt.Errorf(errMarshalRequest, err)
	}

	url := fmt.Sprintf("%s/auth/refresh", a.AuthConfig.URL)
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return Tokens{}, fmt.Errorf(errCreateRequest, err)
	}

	req.Header.Set(contentTypeHeader, contentTypeJSON)

	resp, err := a.httpClient.Do(req)
	if err != nil {
		return Tokens{}, fmt.Errorf(errCallAuthService, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return Tokens{}, appErrors.TokenInvalid
	}

	var tokenResp authServiceTokenResponse
	if err := json.NewDecoder(resp.Body).Decode(&tokenResp); err != nil {
		return Tokens{}, fmt.Errorf(errDecodeResponse, err)
	}

	if !tokenResp.Success {
		return Tokens{}, appErrors.TokenInvalid
	}

	return Tokens{
		AccessToken:  tokenResp.Data.AccessToken,
		RefreshToken: tokenResp.Data.RefreshToken,
	}, nil
}

// Login authenticates a user and returns JWT tokens
// Calls POST /auth/login on auth-service
func (a *AuthProviderService) Login(ctx context.Context, email, password string) (Tokens, error) {
	reqBody := authServiceLoginRequest{
		Email:    email,
		Password: password,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return Tokens{}, fmt.Errorf(errMarshalRequest, err)
	}

	url := fmt.Sprintf("%s/auth/login", a.AuthConfig.URL)
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return Tokens{}, fmt.Errorf(errCreateRequest, err)
	}

	req.Header.Set(contentTypeHeader, contentTypeJSON)

	resp, err := a.httpClient.Do(req)
	if err != nil {
		return Tokens{}, fmt.Errorf(errCallAuthService, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return Tokens{}, fmt.Errorf("authentication failed with status: %d", resp.StatusCode)
	}

	var tokenResp authServiceTokenResponse
	if err := json.NewDecoder(resp.Body).Decode(&tokenResp); err != nil {
		return Tokens{}, fmt.Errorf(errDecodeResponse, err)
	}

	if !tokenResp.Success {
		return Tokens{}, fmt.Errorf("authentication failed: %s", tokenResp.Message)
	}

	return Tokens{
		AccessToken:  tokenResp.Data.AccessToken,
		RefreshToken: tokenResp.Data.RefreshToken,
	}, nil
}

// Register creates a new user in auth-service
// Calls POST /auth/register on auth-service
// Note: This returns user profile, not tokens. Use Login after registration to get tokens.
func (a *AuthProviderService) Register(ctx context.Context, email, password string, roles []string) error {
	reqBody := authServiceRegisterRequest{
		Email:    email,
		Password: password,
		Roles:    roles,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return fmt.Errorf(errMarshalRequest, err)
	}

	url := fmt.Sprintf("%s/auth/register", a.AuthConfig.URL)
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return fmt.Errorf(errCreateRequest, err)
	}

	req.Header.Set(contentTypeHeader, contentTypeJSON)

	resp, err := a.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf(errCallAuthService, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusConflict {
		return fmt.Errorf("user already exists")
	}

	if resp.StatusCode != http.StatusCreated {
		return fmt.Errorf("registration failed with status: %d", resp.StatusCode)
	}

	return nil
}

// VerifyToken checks if a token is valid (returns boolean)
// Calls POST /auth/verify-token on auth-service
func (a *AuthProviderService) VerifyToken(ctx context.Context, tokenStr string) (bool, error) {
	// Remove "Bearer " prefix if present
	if len(tokenStr) > 7 && tokenStr[:7] == "Bearer " {
		tokenStr = tokenStr[7:]
	}

	reqBody := authServiceVerifyRequest{
		Token: tokenStr,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return false, fmt.Errorf(errMarshalRequest, err)
	}

	url := fmt.Sprintf("%s/auth/verify-token", a.AuthConfig.URL)
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return false, fmt.Errorf(errCreateRequest, err)
	}

	req.Header.Set(contentTypeHeader, contentTypeJSON)

	resp, err := a.httpClient.Do(req)
	if err != nil {
		return false, fmt.Errorf(errCallAuthService, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return false, nil
	}

	var verifyResp authServiceVerifyResponse
	if err := json.NewDecoder(resp.Body).Decode(&verifyResp); err != nil {
		return false, fmt.Errorf(errDecodeResponse, err)
	}

	if !verifyResp.Success {
		return false, nil
	}

	// The data map should contain "valid": true/false
	if valid, ok := verifyResp.Data["valid"]; ok {
		return valid, nil
	}

	return false, nil
}
