// Copyright (c) 2026 Aptlogica Technologies Private Limited
// SPDX-License-Identifier: MIT
// Websites: https://www.aptlogica.com | https://www.serenibase.com
// Support: support@aptlogica.com | support@serenibase.com

package auth

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	appErrors "github.com/aptlogica/sereni-base/internal/app-errors"
	"github.com/aptlogica/sereni-base/internal/config"

	"github.com/golang-jwt/jwt/v5"
)

const (
	contentTypeHeader  = "Content-Type"
	contentTypeJSON    = "application/json"
	errMarshalRequest  = "failed to marshal request: %w"
	errCreateRequest   = "failed to create request: %w"
	errCallAuthService = "failed to call auth-service: %w"
	errDecodeResponse  = "failed to decode response: %w"
)

func NewAuthProvider(cfg *config.AuthConfig) (AuthProvider, error) {
	return &AuthProviderService{
		AuthConfig: cfg,
		httpClient: &http.Client{
			Timeout: 10 * time.Second,
		},
	}, nil
}

type AuthProviderService struct {
	AuthConfig *config.AuthConfig
	httpClient *http.Client
}

type AuthServiceLoginRequest struct {
	Id            string   `json:"id"`
	Email         string   `json:"email"`
	EmailVerified bool     `json:"email_verified"`
	Roles         []string `json:"roles"`
}

type AuthServiceTokenResponse struct {
	Success bool   `json:"success"`
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
		TokenType    string `json:"token_type"`
		ExpiresIn    int64  `json:"expires_in"`
	} `json:"data"`
}

type authServiceValidateRequest struct {
	Token string `json:"token"`
}

type authServiceValidateResponse struct {
	Success bool   `json:"success"`
	Code    string `json:"code"`
	Message string `json:"message"`
	Data    struct {
		UserID    string `json:"sub"`
		Email     string `json:"email"`
		Roles     string `json:"roles"` // Changed from []string to string
		TokenType string `json:"token_type"`
		Issuer    string `json:"iss"`
		ExpiresAt int64  `json:"exp"`
		IssuedAt  int64  `json:"iat"`
		NotBefore int64  `json:"nbf"`
	} `json:"data"`
}

type AuthServiceRefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type authServiceVerifyRequest struct {
	Token string `json:"token"`
}

type authServiceVerifyResponse struct {
	Success bool            `json:"success"`
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Data    map[string]bool `json:"data"`
}

// Custom Claims structure (kept for compatibility - used for locally generated tokens)
type CustomClaims struct {
	UserId        string `json:"user_id"`
	Email         string `json:"email"`
	Roles         string `json:"roles,omitempty"`
	EmailVerified bool   `json:"email_verified"`
	jwt.RegisteredClaims
}

// JWT Service Claims structure (for tokens generated by JWT service)
type JWTServiceClaims struct {
	Sub       string `json:"sub"`     // User ID (standard JWT claim)
	UserId    string `json:"user_id"` // User ID (fallback for custom tokens)
	Email     string `json:"email"`
	Roles     string `json:"roles"`      // Roles as string
	TokenType string `json:"token_type"` // "access" or "refresh"
	jwt.RegisteredClaims
}

func (a *AuthProviderService) ValidateToken(ctx context.Context, tokenStr string) (Claims, error) {
	// Remove "Bearer " prefix if present
	if len(tokenStr) > 7 && tokenStr[:7] == "Bearer " {
		tokenStr = tokenStr[7:]
	}

	// Try JWT service validation first
	reqBody := authServiceValidateRequest{
		Token: tokenStr,
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return Claims{}, fmt.Errorf(errMarshalRequest, err)
	}

	url := fmt.Sprintf("%s/auth/validate-token", a.AuthConfig.URL)
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return Claims{}, fmt.Errorf(errCreateRequest, err)
	}

	req.Header.Set(contentTypeHeader, contentTypeJSON)

	resp, err := a.httpClient.Do(req)
	if err != nil {
		return Claims{}, fmt.Errorf(errCallAuthService, err)
	}
	defer resp.Body.Close()

	var validateResp authServiceValidateResponse
	if err := json.NewDecoder(resp.Body).Decode(&validateResp); err != nil {
		return Claims{}, fmt.Errorf(errDecodeResponse, err)
	}

	if !validateResp.Success {
		if validateResp.Code != "TOKEN_EXPIRED" {
			return Claims{}, appErrors.TokenExpired
		}
		return Claims{}, appErrors.TokenInvalid
	}

	return Claims{
		UserId: validateResp.Data.UserID, // User ID from sub or user_id claim
		Roles:  validateResp.Data.Roles,  // Roles from token claims (already a string)
	}, nil
}

func (a *AuthProviderService) RefreshToken(ctx context.Context, reqBody AuthServiceRefreshRequest) (Tokens, error) {
	// Call auth-service /auth/refresh endpoint

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return Tokens{}, fmt.Errorf(errMarshalRequest, err)
	}

	url := fmt.Sprintf("%s/auth/refresh", a.AuthConfig.URL)
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return Tokens{}, fmt.Errorf(errCreateRequest, err)
	}

	req.Header.Set(contentTypeHeader, contentTypeJSON)

	resp, err := a.httpClient.Do(req)
	if err != nil {
		return Tokens{}, fmt.Errorf(errCallAuthService, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return Tokens{}, appErrors.TokenInvalid
	}

	var tokenResp AuthServiceTokenResponse
	if err := json.NewDecoder(resp.Body).Decode(&tokenResp); err != nil {
		return Tokens{}, fmt.Errorf(errDecodeResponse, err)
	}

	if !tokenResp.Success {
		return Tokens{}, appErrors.TokenInvalid
	}

	return Tokens{
		AccessToken:  tokenResp.Data.AccessToken,
		RefreshToken: tokenResp.Data.RefreshToken,
	}, nil
}

// Login authenticates a user and returns JWT tokens
// Calls POST /auth/login on auth-service
func (a *AuthProviderService) Login(ctx context.Context, reqBody AuthServiceLoginRequest) (Tokens, error) {
	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return Tokens{}, fmt.Errorf(errMarshalRequest, err)
	}

	url := fmt.Sprintf("%s/auth/login", a.AuthConfig.URL)
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return Tokens{}, fmt.Errorf(errCreateRequest, err)
	}

	req.Header.Set(contentTypeHeader, contentTypeJSON)

	resp, err := a.httpClient.Do(req)

	if err != nil {
		return Tokens{}, fmt.Errorf(errCallAuthService, err)
	}
	defer resp.Body.Close()

	var tokenResp AuthServiceTokenResponse
	if err := json.NewDecoder(resp.Body).Decode(&tokenResp); err != nil {
		return Tokens{}, fmt.Errorf(errDecodeResponse, err)
	}

	if !tokenResp.Success {
		return Tokens{}, fmt.Errorf("authentication failed: %s", tokenResp.Message)
	}

	return Tokens{
		AccessToken:  tokenResp.Data.AccessToken,
		RefreshToken: tokenResp.Data.RefreshToken,
	}, nil
}
